/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphstream_util_NativePointer */

#ifndef _Included_org_graphstream_util_NativePointer
#define _Included_org_graphstream_util_NativePointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graphstream_util_NativePointer
 * Method:    getPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_graphstream_util_NativePointer_getPointer
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_util_NativePointer
 * Method:    setPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_util_NativePointer_setPointer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
