/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphstream_graph_implementations_NativeElement */

#ifndef _Included_org_graphstream_graph_implementations_NativeElement
#define _Included_org_graphstream_graph_implementations_NativeElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_init
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_uninit
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getAttribute__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getFirstAttributeOf
 * Signature: ([Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getFirstAttributeOf___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getAttribute__Ljava_lang_String_2Ljava_lang_Class_2
  (JNIEnv *, jobject, jstring, jclass);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getFirstAttributeOf
 * Signature: (Ljava/lang/Class;[Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getFirstAttributeOf__Ljava_lang_Class_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jclass, jobjectArray);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getLabel
 * Signature: (Ljava/lang/String;)Ljava/lang/CharSequence;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getNumber
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_graphstream_graph_implementations_NativeElement_getNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getVector
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getVector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_graphstream_graph_implementations_NativeElement_getArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getHash
 * Signature: (Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getHash
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasAttribute
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasAttribute__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasAttribute__Ljava_lang_String_2Ljava_lang_Class_2
  (JNIEnv *, jobject, jstring, jclass);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasLabel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasNumber
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasVector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasVector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasArray
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    hasHash
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graphstream_graph_implementations_NativeElement_hasHash
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getAttributeKeyIterator
 * Signature: ()Ljava/util/Iterator;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getAttributeKeyIterator
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getAttributeKeySet
 * Signature: ()Ljava/lang/Iterable;
 */
JNIEXPORT jobject JNICALL Java_org_graphstream_graph_implementations_NativeElement_getAttributeKeySet
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    clearAttributes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_clearAttributes
  (JNIEnv *, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    addAttribute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_addAttribute
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    changeAttribute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_changeAttribute
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    setAttribute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_setAttribute
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    addAttributes
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_addAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    removeAttribute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_graphstream_graph_implementations_NativeElement_removeAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_graphstream_graph_implementations_NativeElement
 * Method:    getAttributeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_graphstream_graph_implementations_NativeElement_getAttributeCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
